services:
  orgchart:
    image: ghcr.io/dvir001/db-auto-org-chart:latest
    container_name: orgchart
    restart: unless-stopped
    ports:
      - "${APP_PORT:-5000}:${APP_PORT:-5000}"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    volumes:
      - orgchart_data:/app/data
    labels:
        com.docker.compose.project: "docker"
    networks:
      - default

networks:
  default:

volumes:
  orgchart_data:
