services:
  orgchart_dev:
    build: .
    container_name: OrgChart-Dev
    restart: unless-stopped
    ports:
      - "5002:${APP_PORT:-5000}"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    volumes:
      - orgchart_data_dev:/app/data
    labels:
        com.docker.compose.project: "docker"
    networks:
      - orgchart_dev_default

networks:
  orgchart_dev_default:

volumes:
  orgchart_data_dev:
